name: Auto PR Bot

on:
  pull_request:
    types: [closed]   # Trigger when PR is closed
    branches:
      - main

jobs:
  auto-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r automated_scripts/model_update/requirements.txt

      - name: Check if models folder changed
        id: changes
        run: |
          echo "Checking changed files in PR #${{ github.event.pull_request.number }}..."
          CHANGED=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files \
            --paginate -q '.[].filename' | grep '^models/' || true)
          if [ -z "$CHANGED" ]; then
            echo "No changes in models/ folder. Exiting."
            exit 0
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}

      - name: Set up Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "🤖 github-actions 🤖"

      - name: Run auto PR script
        if: success() && steps.changes.outcome == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          python automated_scripts/model_update/update_client_model.py \
            --repo-url "https://github.com/ayushcshah/Sample-App.git" \
            --repo-name "ayushcshah/Sample-App" \
            --branch "autogenerated/${PR_NUMBER}" \
            --file "README.md" \
            --commit-message "Adds Codable for BE PR ${PR_NUMBER}" \
            --pr-title "Adds Codable for BE PR ${PR_NUMBER}" \
            --pr-body "This PR was automatically created for BE PR ${PR_NUMBER}."
